### PR TITLE
Creating synthetic RRB data

### PR DESCRIPTION
**Pull request by robwilkerson**
RRB beneficiaries are unique in that they are issued a RRB HICN and an internal HICN. There is a translation process to convert from the former to the latter. MCT _receives_ the RRB HICN from NGD, but BB stores only the internal HICN. These synthetics will allow us to test our conversion utility.

### CODE REVIEW

**Comment by robwilkerson** [comment]
i can't access the failing check, so someone will have to let me know the nature of the problem.

**Comment by karlmdavis** [comment]
The build failure is spurious: our `Jenkinsfile` just doesn't support building from forks.

**Comment by karlmdavis** [comment]
@robwilkerson and @wryenmeek: Made some changes, as noted in my commit messages. Can you please review?

Note that the build does pass locally.

**Comment by robwilkerson** [comment]
Changes look okay to me, thanks!

**Pull request merged**
